"""Phase-2 Platform Access — Phase K: prove a NEW provider is addable via
registry CONFIG only (no code rewrites). Adds Netlify/Render/Fly.io/Wordfence/
Barracuda/F5 as registry entries and confirms detection + remediation + the
wizard view all work unchanged. Run with --noconftest -p no:cacheprovider.
"""
from __future__ import annotations

import apps.api.services.provider_access_registry as reg
from apps.api.services.platform_access import build_platform_access_view
from apps.api.services.scanner_block_detection import detect_blocking_provider

IPS = ["1.2.3.4", "5.6.7.8"]


def _entry(key, name, *, headers=(), header_values=(), html=()):
    return reg.ProviderAccess(
        key=key, name=name, automation_capable=False, allowlist_method="manual",
        verification_method="scan_recheck", support_url=f"https://{key}.example/",
        detection=reg.DetectionSignals(
            headers=headers, header_values=header_values, challenge_html=html),
        remediation_title=f"{name} is blocking the scanner",
        remediation_problem=f"{name} WAF is blocking the WebHound scanner.",
        remediation_impact="Requests are blocked at the edge.",
        remediation_steps=(
            reg.RemediationStep(f"Open the {name} console."),
            reg.RemediationStep("Allowlist the scanner IPs: {ips}", ips=True),
            reg.RemediationStep("Return to WebHound and Verify Access."),
        ),
        remediation_verification="scan_recheck",
    )


# The six future providers from the spec, defined as DATA only.
_FUTURE = {
    "netlify": _entry("netlify", "Netlify",
                      headers=("x-nf-request-id",), html=("netlify security",)),
    "render": _entry("render", "Render",
                     header_values=(("server", "render"),), headers=("x-render-origin",)),
    "fly": _entry("fly", "Fly.io", headers=("fly-request-id",)),
    "wordfence": _entry("wordfence", "Wordfence",
                        html=("wordfence", "generated by wordfence")),
    "barracuda": _entry("barracuda", "Barracuda",
                        html=("barracuda", "blocked by barracuda")),
    "f5": _entry("f5", "F5 BIG-IP",
                 header_values=(("server", "big-ip"),), html=("the requested url was rejected",)),
}


def _install(monkeypatch):
    for k, v in _FUTURE.items():
        monkeypatch.setitem(reg.PROVIDERS, k, v)


def test_aws_waf_and_gcp_armor_already_present():
    assert "aws_waf" in reg.PROVIDERS and "google_cloud_armor" in reg.PROVIDERS


def test_new_provider_detected_via_config_only(monkeypatch):
    _install(monkeypatch)
    # Netlify, added as DATA only, is now detected by the SAME detector — no code.
    res = reg.detect_provider(headers={"x-nf-request-id": "abc"})
    assert res and res["provider"] == "netlify"
    # And by the block-detection layer (consumes the registry).
    blk = detect_blocking_provider(
        {"challenge_detected": True}, headers={"fly-request-id": "z"})
    assert blk["provider"] == "fly"


def test_new_provider_remediation_renders(monkeypatch):
    _install(monkeypatch)
    pay = reg.render_remediation("wordfence", IPS)
    assert pay and pay["provider"] == "wordfence"
    assert pay["copy_all"] == "1.2.3.4, 5.6.7.8"
    assert sum(1 for s in pay["steps"] if s["copyable"]) == 1


def test_new_provider_flows_through_wizard_view(monkeypatch):
    _install(monkeypatch)
    detection = {
        "provider": "barracuda", "name": "Barracuda", "challenge_detected": True,
        "access_required": True, "automation_capable": False,
        "allowlist_method": "manual", "confidence": 60,
    }
    view = build_platform_access_view(
        detection=detection, trusted_status="pending", scanner_ips=IPS)
    assert view["state"] == "access_required"
    assert view["remediation"]["provider"] == "barracuda"
    # Zero provider-specific code ran — the view is pure registry data.
