import type { GlossaryTerm } from './types'

// Every term the interview prep needs, with practical, exam-ready definitions.
// "SOC reports" = System and Organization Controls (NOT Security Operations Center).
export const GLOSSARY: GlossaryTerm[] = [
  { term: 'ICFR', category: 'SOX', short: 'Internal Control over Financial Reporting',
    definition: 'The system of controls a company relies on to give reasonable assurance that its financial statements are accurate and reliable. IT supports ICFR because most financial data lives in systems (ERP, databases). Weak IT controls can undermine ICFR.' },
  { term: 'SOX 404', category: 'SOX', short: 'Sarbanes-Oxley §404 — management & auditor assess ICFR',
    definition: 'Section 404 of the Sarbanes-Oxley Act of 2002. 404(a): management must assess and report on the effectiveness of ICFR. 404(b): the external auditor must independently attest to it. This is why public companies (like PCA) test IT general controls every year.' },
  { term: 'COSO', category: 'SOX', short: 'Internal-control framework (5 components)',
    definition: 'The Committee of Sponsoring Organizations framework — the standard model for designing/evaluating internal control. Five components: Control Environment, Risk Assessment, Control Activities, Information & Communication, and Monitoring Activities (17 principles).' },
  { term: 'GITC', category: 'GITC', short: 'General IT Controls (= ITGC)',
    definition: 'General Information Technology Controls — foundational controls over the IT environment that support application/financial controls. Four classic domains: logical access, change management, computer operations (incl. backup), and (sometimes) program development/SDLC.' },
  { term: 'ITGC', category: 'GITC', short: 'IT General Controls (= GITC)',
    definition: 'Same thing as GITC — different acronym used interchangeably. If application controls are the locks on each door, ITGCs are the building security that makes those locks trustworthy.' },
  { term: 'PCAOB AS 2201', category: 'Audit', short: 'Audit of ICFR integrated with the financial-statement audit',
    definition: 'Public Company Accounting Oversight Board Auditing Standard 2201 — governs how external auditors perform an integrated audit of internal control over financial reporting. Frames top-down, risk-based testing of controls.' },
  { term: 'PCAOB AS 1105', category: 'Audit', short: 'Audit Evidence standard',
    definition: 'PCAOB standard on audit evidence — evidence must be both sufficient (enough of it) and appropriate (relevant + reliable). The bedrock of why auditors ask for specific artifacts.' },
  { term: 'Test of Design', category: 'Audit', short: 'ToD — is the control capable of working?',
    definition: 'Evaluating whether a control, if operating as described, would prevent or detect the risk. Done via inquiry, observation, and walkthroughs. You test design before you test operation.' },
  { term: 'Test of Operating Effectiveness', category: 'Audit', short: 'ToE — did the control actually work all period?',
    definition: 'Evaluating whether the control operated consistently throughout the audit period — by re-performance, inspection of evidence, and sampling. A control can be well-designed but fail to operate (e.g. reviews skipped).' },
  { term: 'roll-forward', category: 'Audit', short: 'Extend interim testing to year-end',
    definition: 'When controls are tested at an interim date, roll-forward procedures cover the remaining period to year-end (inquiry + a smaller sample) so the conclusion holds for the full fiscal year.' },
  { term: 'control owner', category: 'Audit', short: 'Person accountable for a control operating',
    definition: 'The individual responsible for performing/owning a specific control (e.g. the manager who runs quarterly access reviews). Auditors interview them in walkthroughs.' },
  { term: 'key control', category: 'Audit', short: 'Control that primarily addresses a risk',
    definition: 'A control that, on its own, is relied upon to prevent or detect a material misstatement for a given risk. Key controls get the most testing; non-key controls support them.' },
  { term: 'material weakness', category: 'SOX', short: 'Reasonable possibility of a material misstatement',
    definition: 'The most severe control deficiency: a deficiency (or combination) such that there is a reasonable possibility that a material misstatement of the financials will not be prevented or detected timely. Must be disclosed publicly.' },
  { term: 'significant deficiency', category: 'SOX', short: 'Less severe than material weakness, still important',
    definition: 'A deficiency less severe than a material weakness but important enough to merit attention by those responsible for oversight (audit committee). Not necessarily publicly disclosed.' },
  { term: 'audit evidence', category: 'Audit', short: 'Information used to support the audit conclusion',
    definition: 'Anything the auditor uses to reach a conclusion — tickets, screenshots, system exports, approvals, logs, re-performance. Quality matters more than quantity.' },
  { term: 'sufficient evidence', category: 'Audit', short: 'Enough evidence (quantity)',
    definition: 'The measure of the QUANTITY of audit evidence. More risk → larger samples → more evidence needed.' },
  { term: 'appropriate evidence', category: 'Audit', short: 'Relevant + reliable evidence (quality)',
    definition: 'The measure of QUALITY: evidence must be relevant (addresses the assertion) and reliable (e.g. system-generated > screenshot > verbal). Sufficient + appropriate together support a conclusion (AS 1105).' },
  { term: 'population', category: 'Audit', short: 'The complete set of items a control acted on',
    definition: 'The full set of items subject to a control during the period (e.g. all 1,240 changes migrated to prod). The auditor selects a sample from the population — so a complete, accurate population is itself a key piece of evidence.' },
  { term: 'sample', category: 'Audit', short: 'Subset selected for testing',
    definition: 'A subset of the population selected (randomly or by judgment) to test. Sample size scales with control frequency and risk (e.g. daily control → 25; quarterly → 2).' },
  { term: 'exception', category: 'Audit', short: 'A sampled item that failed the control',
    definition: 'An instance where the control did not operate as intended (e.g. a change with no approval). Exceptions are investigated for root cause and impact; even one can break a conclusion depending on context.' },
  { term: 'remediation', category: 'Audit', short: 'Fixing a deficiency + re-testing',
    definition: 'The corrective action taken after a deficiency/exception, plus the evidence and re-test demonstrating the control now operates. Auditors want a remediation plan with owners and dates.' },
  { term: 'access review', category: 'IAM', short: 'Periodic recertification of who has access',
    definition: 'A periodic (often quarterly) review where managers/owners confirm each user still needs their access; inappropriate access is removed. A core ITGC — evidence includes the review record, the population pulled, and removals actioned.' },
  { term: 'least privilege', category: 'IAM', short: 'Only the access needed for the job',
    definition: 'The principle that each user/account gets the minimum access required to do their work — nothing more. Reduces blast radius and audit risk.' },
  { term: 'privileged account', category: 'IAM', short: 'Admin/elevated access',
    definition: 'An account with elevated rights (domain admin, DBA, sysadmin). High risk → tighter controls: limited count, MFA, logging, and more frequent review.' },
  { term: 'provisioning', category: 'IAM', short: 'Granting access (Joiner)',
    definition: 'Creating accounts and granting access when someone joins or changes roles — should be approved and role-based. Evidence: approved request tied to the access granted.' },
  { term: 'deprovisioning', category: 'IAM', short: 'Removing access (Leaver)',
    definition: 'Removing/disabling access when someone leaves or no longer needs it — timeliness is critical. The classic audit test: pick terminated users and confirm access was removed promptly.' },
  { term: 'authentication', category: 'IAM', short: 'Proving who you are (authN)',
    definition: 'Verifying identity — passwords, MFA, certificates. Answers "are you who you claim to be?"' },
  { term: 'authorization', category: 'IAM', short: 'What you are allowed to do (authZ)',
    definition: 'Determining what an authenticated identity may access/do — roles, groups, permissions. Answers "are you allowed to do this?" AuthN comes before authZ.' },
  { term: 'MFA', category: 'IAM', short: 'Multi-factor authentication',
    definition: 'Requiring two+ factors (something you know/have/are). A standard logical-access control; auditors check it is enforced, especially for privileged and remote access.' },
  { term: 'Active Directory', category: 'IAM', short: 'On-prem Microsoft identity/directory service',
    definition: 'Microsoft’s on-premises directory — manages users, computers, groups, and authentication (Kerberos/LDAP) via domain controllers. Organized into OUs; access granted via security groups.' },
  { term: 'Entra ID', category: 'IAM', short: 'Microsoft cloud identity (formerly Azure AD)',
    definition: 'Microsoft’s cloud identity platform (renamed from Azure AD) — identity for Microsoft 365 and cloud apps, with conditional access, MFA, and SSO. Often synced from on-prem AD.' },
  { term: 'OU', category: 'IAM', short: 'Organizational Unit (AD container)',
    definition: 'An Organizational Unit — a container in Active Directory used to organize users/computers and apply Group Policy (GPO) and delegated administration.' },
  { term: 'security group', category: 'IAM', short: 'Group used to grant access',
    definition: 'An AD/Entra group whose membership grants permissions. Role-based access typically maps roles → groups → resources, which makes reviews and provisioning auditable.' },
  { term: 'service account', category: 'IAM', short: 'Non-human account for apps/automation',
    definition: 'An account used by an application/service rather than a person. Risky because they’re often privileged, shared, and rarely rotated — auditors check ownership, necessity, and password/secret management.' },
  { term: 'break-glass account', category: 'IAM', short: 'Emergency highly-privileged account',
    definition: 'A tightly controlled emergency admin account used only when normal access fails. Controls: sealed/vaulted credentials, alerting on use, and after-the-fact review.' },
  { term: 'JML', category: 'IAM', short: 'Joiner / Mover / Leaver lifecycle',
    definition: 'The identity lifecycle: Joiner (provision), Mover (adjust access on role change — and remove old access), Leaver (deprovision). Movers are the most-missed leg because old access lingers.' },
  { term: 'CAB', category: 'Change', short: 'Change Advisory Board',
    definition: 'A group that reviews/approves significant changes before they go to production — balancing benefit vs risk. Evidence: CAB minutes/approvals tied to the change ticket.' },
  { term: 'CCB', category: 'Change', short: 'Change Control Board',
    definition: 'Essentially the same role as a CAB in many shops — the governance body approving changes. Naming varies by organization.' },
  { term: 'RFC', category: 'Change', short: 'Request for Change',
    definition: 'The formal record proposing a change — description, risk, test plan, backout plan, approvals. The anchor artifact for change-management testing.' },
  { term: 'emergency change', category: 'Change', short: 'Expedited change with after-the-fact approval',
    definition: 'A change made urgently (e.g. to fix an outage) under an expedited path, with documented justification and retrospective approval. Auditors check these aren’t abused to bypass normal controls.' },
  { term: 'SDLC', category: 'Change', short: 'Software Development Life Cycle',
    definition: 'The governed process for building/changing software (requirements → design → build → test → deploy → maintain). SDLC controls give assurance changes are authorized, tested, and segregated from production.' },
  { term: 'migration', category: 'Change', short: 'Moving a change into production',
    definition: 'The act of promoting code/config from test to production. Controlled migrations require approval, successful test evidence, and segregation of duties (the developer shouldn’t self-deploy unreviewed).' },
  { term: 'backout plan', category: 'Change', short: 'How to reverse a failed change',
    definition: 'A documented plan to revert a change if it fails in production (rollback steps, restore points). A well-run change process requires one before approval.' },
  { term: 'RTO', category: 'DR', short: 'Recovery Time Objective',
    definition: 'The maximum acceptable time to restore a system/process after disruption. "How long can we be down?" Drives DR architecture and is tested via restore exercises.' },
  { term: 'RPO', category: 'DR', short: 'Recovery Point Objective',
    definition: 'The maximum acceptable amount of data loss measured in time. "How much data can we afford to lose?" An RPO of 1 hour implies backups/replication at least hourly.' },
  { term: 'DRP', category: 'DR', short: 'Disaster Recovery Plan',
    definition: 'The documented IT plan to recover systems/infrastructure after a disaster. Evidence auditors want: the plan, recovery roles, and proof of periodic testing.' },
  { term: 'BCP', category: 'DR', short: 'Business Continuity Plan',
    definition: 'The broader plan to keep the business operating during disruption (people, processes, facilities) — DR is the IT subset of BCP.' },
  { term: 'backup restore test', category: 'DR', short: 'Proving backups actually restore',
    definition: 'A periodic test that restores from backup to verify data is recoverable and meets RTO/RPO. A backup you’ve never restored is an assumption, not a control — auditors want restore evidence, not just backup-success logs.' },
  { term: 'data center review', category: 'DR', short: 'Assessing facility controls',
    definition: 'Review of the facility hosting systems — physical access, environmental controls (power/cooling/fire), and monitoring. For PCA (manufacturing), plant/data-center physical controls matter.' },
  { term: 'physical security', category: 'DR', short: 'Protecting facilities/hardware',
    definition: 'Controls protecting physical assets — badge access, cameras, visitor logs, locked racks. Distinct from logical security.' },
  { term: 'logical security', category: 'IAM', short: 'Protecting systems/data via software controls',
    definition: 'Controls within systems — authentication, authorization, encryption, logging. The "logical" counterpart to physical security.' },
  { term: 'SLA', category: 'Vendor', short: 'Service Level Agreement',
    definition: 'A contractual commitment on service performance (uptime, response time, recovery). Relevant to vendor/third-party risk and to operations controls.' },
  { term: 'SOC 1', category: 'SOC', short: 'Controls relevant to financial reporting',
    definition: 'A System and Organization Controls report focused on a service organization’s controls relevant to user entities’ ICFR. The report you rely on when a vendor processes financially-relevant data (e.g. payroll). Reported under SSAE 18 (SOC = System and Organization Controls, NOT Security Operations Center).' },
  { term: 'SOC 2', category: 'SOC', short: 'Controls over the Trust Services Criteria',
    definition: 'A SOC report on controls relevant to Security, Availability, Processing Integrity, Confidentiality, and/or Privacy (the Trust Services Criteria). Used for security/operational assurance of a vendor — not primarily for financial reporting.' },
  { term: 'SOC 3', category: 'SOC', short: 'Public, general-use summary of SOC 2',
    definition: 'A general-use, public-facing summary report of SOC 2 results — no detailed control/test descriptions. Marketing-friendly; not enough detail for audit reliance.' },
  { term: 'Type I', category: 'SOC', short: 'Design at a point in time',
    definition: 'A SOC report opining on whether controls are suitably DESIGNED as of a specific date. No operating-effectiveness testing over time — weaker assurance.' },
  { term: 'Type II', category: 'SOC', short: 'Design + operating effectiveness over a period',
    definition: 'A SOC report covering both design AND operating effectiveness over a period (e.g. 6–12 months) with test results. Stronger assurance — what you want for reliance.' },
  { term: 'CUEC', category: 'SOC', short: 'Complementary User Entity Controls',
    definition: 'Controls the SOC report assumes YOU (the user entity) perform for the vendor’s controls to be effective (e.g. "user is responsible for reviewing access to the application"). Reviewing CUECs is a required step when relying on a SOC report.' },
  { term: 'bridge letter', category: 'SOC', short: 'Gap letter between SOC period and year-end',
    definition: 'A "gap" or "gap-period" letter from the service org covering the time between the SOC report period-end and the user’s fiscal year-end, attesting no material changes. Bridges a SOC report that doesn’t fully cover your year.' },
  { term: 'subservice organization', category: 'SOC', short: 'A vendor’s vendor',
    definition: 'A third party that the service organization itself relies on (e.g. a SaaS vendor’s cloud host). The SOC report handles them via the carve-out or inclusive method.' },
  { term: 'carve-out method', category: 'SOC', short: 'Subservice org excluded from the report',
    definition: 'The SOC report describes the subservice org’s services but EXCLUDES its controls from the description/testing — you must obtain separate assurance (e.g. the cloud host’s own SOC report).' },
  { term: 'inclusive method', category: 'SOC', short: 'Subservice org included in the report',
    definition: 'The SOC report INCLUDES the subservice org’s relevant controls within its description and testing scope. Less common; gives you coverage in one report.' },
  { term: 'risk register', category: 'Risk', short: 'Catalog of risks + controls + owners',
    definition: 'A living inventory of identified risks with likelihood/impact, owners, and the controls mitigating them. Drives where audit effort is focused.' },
  { term: 'inherent risk', category: 'Risk', short: 'Risk before controls',
    definition: 'The level of risk in the absence of any controls — the "natural" exposure of an activity.' },
  { term: 'residual risk', category: 'Risk', short: 'Risk after controls',
    definition: 'The risk remaining after controls are applied. Residual risk should sit at or below the organization’s risk appetite.' },
  { term: 'risk appetite', category: 'Risk', short: 'How much risk the org will accept',
    definition: 'The amount/type of risk an organization is willing to accept in pursuit of objectives. Sets the bar for whether residual risk is acceptable or needs more control.' },
  { term: 'compensating control', category: 'Risk', short: 'Alternative control covering a gap',
    definition: 'A control that mitigates a risk when the primary/expected control is absent or not feasible (e.g. detailed log review compensating for weak segregation of duties). Must actually address the same risk to be relied upon.' },
]
