import type { Lab } from './types'

export const LABS: Lab[] = [
  {
    id: 'access-review-checklist',
    title: 'Build an access-review evidence checklist',
    scenario: 'Your senior asks you to prepare to test the quarterly user access review for the ERP system.',
    goal: 'Know exactly what evidence makes an access review defensible.',
    steps: [
      'List the population needed: a system-generated user listing pulled at a known date.',
      'Confirm completeness of the population (how do you know it’s every user?).',
      'Identify the reviewer and their dated sign-off record.',
      'For any access flagged inappropriate, find the ticket proving removal was actioned.',
      'Check timing: was the review performed within the required quarter?',
      'Note red flags: reviews with no removals ever, undated evidence, no defined population.',
    ],
    deliverable: 'A checklist mapping each evidence item → why an auditor needs it → what makes it strong vs weak.',
    tip: 'If you can’t tie it to a complete population and a date, it’s weak evidence.',
  },
  {
    id: 'terminated-user-sample',
    title: 'Review a fake terminated-user sample',
    scenario: 'HR gives you 5 terminations. IT provides access-disabled dates. Policy: disable within 24h.',
    goal: 'Practice spotting deprovisioning exceptions.',
    steps: [
      'For each user, compare termination date to access-disabled date.',
      'Flag any gap beyond the 24-hour policy window as an exception.',
      'For exceptions, ask: was the account used after termination? Did it have financially-relevant access?',
      'Decide whether it looks isolated or systemic.',
      'Draft how you’d document the exception and what remediation you’d request.',
    ],
    deliverable: 'An exception log: user, term date, disabled date, gap, severity rationale, remediation ask.',
    tip: 'Source the population from HR, independent of IT — that’s what makes it complete.',
  },
  {
    id: 'change-ticket-review',
    title: 'Review a fake change ticket',
    scenario: 'A change to the billing system was deployed to production. You have the ticket.',
    goal: 'Confirm a production change followed the control.',
    steps: [
      'Find the request describing the change, its risk, and a backout plan.',
      'Find evidence it was tested in a non-prod environment.',
      'Confirm approval by the right person — and that it predates deployment.',
      'Confirm the deployer ≠ the developer (segregation of duties).',
      'Confirm what went to prod matches what was approved.',
    ],
    deliverable: 'A pass/exception note per control attribute (request, test, approval-before-deploy, SoD).',
    tip: 'The classic exception is approval granted AFTER the change was already live.',
  },
  {
    id: 'risk-control-matrix',
    title: 'Build a risk-control matrix (RCM)',
    scenario: 'You’re documenting controls for the logical-access domain of a financial app.',
    goal: 'Connect risks → controls → tests the way a SOX program does.',
    steps: [
      'List 3–4 risks (e.g. unauthorized access, access not removed on termination, excess privilege).',
      'For each risk, name the key control that addresses it.',
      'Mark whether each control is preventive or detective.',
      'Define the test of operating effectiveness (population, sample, what you inspect).',
      'Note the evidence you’d collect for each.',
    ],
    deliverable: 'A small RCM table: Risk | Key Control | Type | Test | Evidence.',
    tip: 'A "key control" is one you’d rely on by itself to address the risk — those get the most testing.',
  },
  {
    id: 'soc-report-summary',
    title: 'Review a mock SOC 1 report summary',
    scenario: 'A payroll vendor sends a SOC 1 Type II. Their period ends 3 months before your year-end.',
    goal: 'Practice the SOC review checklist.',
    steps: [
      'Confirm report type (SOC 1 for financial reliance) and that it’s Type II.',
      'Check the coverage period vs your fiscal year — identify the 3-month gap.',
      'Decide what closes the gap (request a bridge letter).',
      'Read the opinion for any qualification; scan test results for exceptions on relied-upon controls.',
      'List the CUECs and confirm whether YOUR org actually performs them.',
      'Check how subservice orgs are handled (carve-out vs inclusive).',
    ],
    deliverable: 'A one-page SOC review memo with conclusion + items to flag.',
    tip: 'A gap period isn’t a dealbreaker — a bridge letter usually closes it.',
  },
  {
    id: 'dr-evidence-checklist',
    title: 'Build a DR evidence checklist',
    scenario: 'You’re testing backup & recovery for a financially-significant system.',
    goal: 'Distinguish backup logs from real recoverability evidence.',
    steps: [
      'Identify the system’s RTO and RPO.',
      'Confirm backup frequency supports the RPO.',
      'Find evidence of a periodic RESTORE test (not just backup-success logs).',
      'Confirm the restore met the RTO/RPO.',
      'Note physical/environmental controls if a data-center review is in scope.',
    ],
    deliverable: 'A checklist separating "backup configured" evidence from "recoverability proven" evidence.',
    tip: 'A backup you’ve never restored is an assumption, not a control.',
  },
  {
    id: 'evidence-request-tracker',
    title: 'Create an auditor evidence request tracker (PBC list)',
    scenario: 'You’re coordinating evidence across 10 controls and 4 control owners.',
    goal: 'Run an audit the way it actually gets run day-to-day.',
    steps: [
      'Define columns: Control | Owner | Evidence requested | Requested date | Received date | Status | Location.',
      'Add a few sample rows across access, change, and operations controls.',
      'Decide your follow-up cadence for open items.',
      'Decide how you’d escalate a genuine blocker (and when).',
      'Note where artifacts are stored (e.g. SharePoint with version history).',
    ],
    deliverable: 'A working tracker template you could hand to a control owner today.',
    tip: 'The worst move near year-end is going quiet. Transparent status + early escalation wins.',
  },
]
