"""Phase 8D: WADE Executive Reasoning.

Generates customer-safe executive summaries from finding sets.
No scare tactics, no unsupported claims, no jargon.
Advisory only — does NOT modify production findings.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from scripts.wade.reasoning.models import Finding, PriorityLevel


_SEVERITY_WEIGHT: dict[str, int] = {
    "exposed_env": 10,
    "exposed_git": 9,
    "exposed_backup_file": 8,
    "suspicious_javascript": 8,
    "threat_intel_match": 7,
    "tls_expiry": 7,
    "third_party_script_risk": 6,
    "tls_misconfiguration": 5,
    "graphql_exposure": 5,
    "swagger_exposure": 4,
    "api_exposure": 4,
    "missing_csp": 4,
    "missing_hsts": 4,
    "wordpress_xmlrpc": 4,
    "mixed_content": 3,
    "missing_x_frame_options": 3,
    "missing_secure_cookie": 3,
    "missing_httponly_cookie": 3,
    "missing_samesite_cookie": 2,
    "cloudflare_challenge_page": 0,
    "vercel_deployment_protection": 0,
    "provider_blocked_scan": 0,
}

_CUSTOMER_LANGUAGE: dict[str, str] = {
    "exposed_env": "configuration files containing sensitive information were accessible",
    "exposed_git": "version-control files containing source code history were accessible",
    "exposed_backup_file": "backup files potentially containing sensitive data were accessible",
    "suspicious_javascript": "changes to website scripts were detected that warrant review",
    "threat_intel_match": (
        "a network address associated with threat-intelligence reports was observed"
    ),
    "missing_csp": "a browser security policy controlling which scripts can run was absent",
    "missing_hsts": "a policy enforcing encrypted connections was absent",
    "third_party_script_risk": "third-party scripts from external domains were loaded",
    "tls_misconfiguration": "the encrypted connection configuration uses outdated settings",
    "tls_expiry": "the security certificate for encrypted connections has expired",
    "cloudflare_challenge_page": (
        "the site's security provider presented a verification challenge during scanning "
        "(this is a security feature, not a vulnerability)"
    ),
    "vercel_deployment_protection": (
        "the site's deployment protection was active during scanning "
        "(this is a security feature, not a vulnerability)"
    ),
    "provider_blocked_scan": (
        "scanning was restricted by the site's security provider "
        "(expected behavior)"
    ),
    "graphql_exposure": "an API exploration endpoint was publicly accessible",
    "swagger_exposure": "API documentation was publicly accessible",
    "api_exposure": "API endpoints without authentication were detected",
    "missing_x_frame_options": "protection against clickjacking was absent",
    "missing_secure_cookie": "session cookies were configured without encryption protection",
    "missing_httponly_cookie": "session cookies were accessible to page scripts",
    "missing_samesite_cookie": "session cookies lacked cross-site request protection",
    "mixed_content": "some page resources were loaded over unencrypted connections",
    "wordpress_xmlrpc": "a legacy remote-access endpoint was enabled",
}

_INFORMATIONAL_TYPES = frozenset({
    "cloudflare_challenge_page",
    "vercel_deployment_protection",
    "provider_blocked_scan",
})


@dataclass
class ExecutiveSummary:
    """Customer-safe executive summary for a scan result set."""
    overall_posture: str       # e.g. "Needs Attention", "Strong", "Critical Issues Found"
    critical_count: int
    high_count: int
    medium_count: int
    low_count: int
    informational_count: int
    top_concerns: list[str]
    immediate_actions: list[str]
    positive_observations: list[str]
    narrative: str
    advisory_note: str = (
        "This summary is generated by the WADE Advisory Engine and does not "
        "represent a guarantee of security or a complete security assessment."
    )

    def summary_dict(self) -> dict[str, Any]:
        return {
            "overall_posture": self.overall_posture,
            "critical": self.critical_count,
            "high": self.high_count,
            "medium": self.medium_count,
            "low": self.low_count,
            "informational": self.informational_count,
            "top_concerns": self.top_concerns,
            "immediate_actions": self.immediate_actions,
            "narrative": self.narrative,
        }


def generate_executive_summary(
    findings: list[Finding],
    *,
    correlation_patterns: list[str] | None = None,
    attack_chain_names: list[str] | None = None,
    priority_levels: dict[str, PriorityLevel] | None = None,
) -> ExecutiveSummary:
    """Generate a customer-safe executive summary. Advisory only."""
    if not findings:
        return ExecutiveSummary(
            overall_posture="No findings to summarize",
            critical_count=0,
            high_count=0,
            medium_count=0,
            low_count=0,
            informational_count=0,
            top_concerns=[],
            immediate_actions=[],
            positive_observations=["No findings detected in this scan"],
            narrative="The scan completed without identifying any security findings.",
        )

    pl = priority_levels or {}
    critical, high, medium, low, info = 0, 0, 0, 0, 0
    top_concerns: list[str] = []
    immediate_actions: list[str] = []

    weighted = sorted(
        findings,
        key=lambda f: _SEVERITY_WEIGHT.get(f.finding_type, 2),
        reverse=True,
    )

    for f in weighted:
        if f.finding_type in _INFORMATIONAL_TYPES:
            info += 1
            continue
        w = _SEVERITY_WEIGHT.get(f.finding_type, 2)
        level = pl.get(f.finding_type)
        if level == PriorityLevel.IMMEDIATE or w >= 8:
            critical += 1
        elif level == PriorityLevel.HIGH or w >= 6:
            high += 1
        elif level == PriorityLevel.MEDIUM or w >= 3:
            medium += 1
        else:
            low += 1

    for f in weighted[:3]:
        if f.finding_type in _INFORMATIONAL_TYPES:
            continue
        lang = _CUSTOMER_LANGUAGE.get(
            f.finding_type, f.finding_type.replace("_", " ")
        )
        top_concerns.append(lang.capitalize())

    if critical > 0:
        immediate_actions.append(
            "Review and remediate the most critical findings as soon as possible"
        )
    if "exposed_env" in {f.finding_type for f in findings}:
        immediate_actions.append(
            "Rotate all credentials found in exposed configuration files immediately"
        )
    if "tls_expiry" in {f.finding_type for f in findings}:
        immediate_actions.append("Renew the expired security certificate")
    if attack_chain_names:
        immediate_actions.append(
            f"Review advisory attack-chain patterns identified: "
            f"{', '.join(attack_chain_names)}"
        )

    positive: list[str] = []
    if info > 0:
        positive.append(
            "Security provider protections (WAF/deployment protection) are active"
        )
    if critical == 0 and high == 0:
        positive.append("No critical or high-priority findings detected")

    total_real = len([f for f in findings if f.finding_type not in _INFORMATIONAL_TYPES])
    if critical >= 3 or (critical > 0 and high > 0):
        posture = "Critical Issues Found — Immediate Action Required"
    elif critical > 0:
        posture = "Significant Issues Found"
    elif high > 0:
        posture = "Needs Attention"
    elif medium > 0:
        posture = "Minor Improvements Recommended"
    else:
        posture = "Good Security Posture"

    narrative_parts = [
        f"This scan identified {total_real} security finding"
        f"{'s' if total_real != 1 else ''}."
    ]
    if critical > 0:
        narrative_parts.append(
            f"{critical} finding{'s' if critical != 1 else ''} warrant immediate attention."
        )
    if info > 0:
        narrative_parts.append(
            f"{info} informational item{'s relate' if info != 1 else ' relates'} "
            "to provider security controls and do not represent customer-introduced risk."
        )
    if correlation_patterns:
        narrative_parts.append(
            f"The advisory engine identified {len(correlation_patterns)} "
            "compound pattern(s) across findings, suggesting these may share "
            "a common root cause."
        )

    return ExecutiveSummary(
        overall_posture=posture,
        critical_count=critical,
        high_count=high,
        medium_count=medium,
        low_count=low,
        informational_count=info,
        top_concerns=top_concerns,
        immediate_actions=immediate_actions,
        positive_observations=positive,
        narrative=" ".join(narrative_parts),
    )
