"""Phase 7A: Hybrid lexical + dense retrieval over the unified chunk index.

Modes:
  lexical_only — TF-IDF BM25-style (no model needed)
  dense_only   — cosine similarity over L2-normalized embeddings
  hybrid       — weighted combination: 0.35 lexical + 0.65 dense (configurable)

Import: from scripts.ai.hybrid_retrieval import load_retriever
No cloud APIs. Requires corpus/indexes/dense/ artifacts for dense modes.
"""
from __future__ import annotations
import json
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

# numpy is optional at import time; only required for dense modes
try:
    import numpy as np
    _HAS_NP = True
except ImportError:  # CI environment (pytest + jsonschema only)
    np = None  # type: ignore[assignment]
    _HAS_NP = False

ROOT = Path(__file__).resolve().parent.parent.parent
DOC_CHUNKS_PATH = ROOT / "corpus" / "normalized" / "unified_chunks.jsonl"
# CONTROL-2C: the canonical, code-aware chunk set (regenerated by
# build_canonical_brain_index.py — NOT committed). Preferred when present.
CANONICAL_CHUNKS_PATH = ROOT / "corpus" / "index" / "canonical_chunks.jsonl"
CANONICAL_DENSE_DIR = ROOT / "corpus" / "index" / "dense"
CHUNKS_PATH = DOC_CHUNKS_PATH  # back-compat alias
INDEX_DIR = ROOT / "corpus" / "indexes" / "dense"
EMB_PATH = INDEX_DIR / "chunk_embeddings.npy"
META_PATH = INDEX_DIR / "chunk_embedding_meta.json"
CFG_PATH = INDEX_DIR / "dense_index_config.json"

DEFAULT_LEX_W = 0.35
DEFAULT_DENSE_W = 0.65
SNIPPET_LEN = 200


def _tok(text: str) -> list[str]:
    return re.findall(r"[a-z0-9]+", text.lower())


# ── CONTROL-2E: code-symbol ranking ────────────────────────────────────────────
# When a query exactly matches a production module/class/function name, real CODE
# should outrank generic docs. Boosts are metadata-driven (file stem + symbol
# title + source tier) and generalize — no per-concept hardcoding. They only ADD
# to scores, so they never reduce the CONTROL-2D >=8/10 found count.
_SYMBOL_BOOST_MODULE = 0.25   # query contains ALL of a code module's stem tokens
_SYMBOL_BOOST_SYMBOL = 0.12   # query contains ALL of a code chunk's symbol tokens
_SOURCE_TIER_WEIGHT = 0.01    # small tie-break: (8 - tier) * weight
_CODE_SOURCE_TYPE = "production_code"
_DOC_SOURCE_TYPES = {"internal_doc", "official_doc", "official_repo", "provider_doc"}


def _ident_tokens(text: str) -> list[str]:
    """Split an identifier/path-stem into tokens: 'tls_checker' -> [tls, checker]."""
    return [t for t in re.split(r"[^a-z0-9]+", (text or "").lower()) if t]


def _source_tier(chunk: dict) -> int:
    """1 production code · 2 API code · 3 WADE code · 4 tests · 5 tech docs ·
    6 knowledge notes · 7 planning/other (lower = higher priority)."""
    st = chunk.get("source_type", "")
    tags = chunk.get("topic_tags") or []
    tagstr = " ".join(tags).lower() if isinstance(tags, list) else str(tags).lower()
    fp = chunk.get("file_path", "").lower()
    if st == _CODE_SOURCE_TYPE:
        if "test" in tagstr or "/test" in fp:
            return 4
        if "wade" in tagstr or "/wade" in fp:
            return 3
        if "api" in tagstr or "apps/api" in fp:
            return 2
        return 1
    if st in _DOC_SOURCE_TYPES:
        return 5
    if "knowledge" in st or "knowledge" in fp:
        return 6
    return 7


def _symbol_boost(qtokens: set[str], chunk: dict) -> float:
    """Boost code chunks whose module-stem or symbol name is fully named by the query."""
    if chunk.get("source_type") != _CODE_SOURCE_TYPE:
        return 0.0
    boost = 0.0
    stem = chunk.get("file_path", "").rsplit("/", 1)[-1].rsplit(".", 1)[0]
    stem_toks = _ident_tokens(stem)
    if stem_toks and all(t in qtokens for t in stem_toks):
        boost = max(boost, _SYMBOL_BOOST_MODULE)
    sym_toks = _ident_tokens(chunk.get("title", ""))
    if sym_toks and sym_toks != ["module"] and all(t in qtokens for t in sym_toks):
        boost = max(boost, _SYMBOL_BOOST_SYMBOL)
    return boost


class HybridRetriever:
    """Lexical + dense hybrid retriever over chunked knowledge base."""

    def __init__(
        self,
        chunks: list[dict],
        embeddings: "np.ndarray | None",
        meta: list[dict],
        model_name: str = "all-MiniLM-L6-v2",
        lexical_weight: float = DEFAULT_LEX_W,
        dense_weight: float = DEFAULT_DENSE_W,
    ) -> None:
        self.chunks = chunks
        self.embeddings = embeddings
        self.meta = meta
        self.model_name = model_name
        self.lex_w = lexical_weight
        self.dense_w = dense_weight
        self._model = None  # lazy-loaded on first dense call
        self._tf, self._df, self._n = self._build_lex_index()

    # ── Lexical index ─────────────────────────────────────────────────────────

    def _build_lex_index(self):
        tf: dict[int, Counter] = {}
        df: dict[str, int] = defaultdict(int)
        for i, c in enumerate(self.chunks):
            counts = Counter(_tok(c.get("text", "")))
            tf[i] = counts
            for t in counts:
                df[t] += 1
        return tf, df, len(self.chunks)

    def _lex_score(self, query: str, k: int) -> list[tuple[int, float]]:
        scores: dict[int, float] = {}
        for term in _tok(query):
            idf = math.log((self._n + 1) / (self._df.get(term, 0) + 1)) + 1
            for i, counts in self._tf.items():
                if term in counts:
                    scores[i] = scores.get(i, 0.0) + counts[term] * idf
        top = sorted(scores, key=lambda x: scores[x], reverse=True)[:k]
        return [(i, scores[i]) for i in top]

    # ── Dense retrieval ───────────────────────────────────────────────────────

    def _load_model(self) -> bool:
        if self._model is not None:
            return True
        try:
            from sentence_transformers import SentenceTransformer
            self._model = SentenceTransformer(self.model_name)
            return True
        except ImportError:
            return False

    def _dense_score(self, query: str, k: int) -> list[tuple[int, float]]:
        if self.embeddings is None or not _HAS_NP or not self._load_model():
            return []
        q_emb = self._model.encode(
            [query], normalize_embeddings=True, convert_to_numpy=True
        )[0]
        sims = (self.embeddings @ q_emb).tolist()
        top = sorted(range(len(sims)), key=lambda x: sims[x], reverse=True)[:k]
        return [(i, float(sims[i])) for i in top]

    # ── Score normalization ───────────────────────────────────────────────────

    @staticmethod
    def _norm(scored: list[tuple[int, float]]) -> dict[int, float]:
        if not scored:
            return {}
        max_s = max(s for _, s in scored)
        if max_s <= 0:
            return {i: 0.0 for i, _ in scored}
        return {i: s / max_s for i, s in scored}

    # ── Result assembly ───────────────────────────────────────────────────────

    def _make_result(
        self, rank: int, idx: int, lex_s: float, den_s: float, hyb_s: float, mode: str
    ) -> dict:
        c = self.chunks[idx]
        text = c.get("text", "")
        snippet = text[:SNIPPET_LEN].replace("\n", " ").strip()
        return {
            "rank": rank,
            "score": round(hyb_s, 4),
            "lexical_score": round(lex_s, 4),
            "dense_score": round(den_s, 4),
            "hybrid_score": round(hyb_s, 4),
            "chunk_id": c.get("chunk_id", ""),
            "doc_id": c.get("doc_id", ""),
            "title": c.get("title", ""),
            "source_type": c.get("source_type", ""),
            "authority_tier": c.get("authority_tier", ""),
            "source_url": c.get("source_url", ""),
            "file_path": c.get("file_path", ""),
            "phase": c.get("phase", ""),
            "snippet": snippet,
            "mode": mode,
        }

    # ── Public API ────────────────────────────────────────────────────────────

    def _rerank_bonus(self, qtokens: set[str], idx: int) -> float:
        """CONTROL-2E: symbol boost + source-tier tie-break (additive)."""
        c = self.chunks[idx]
        return _symbol_boost(qtokens, c) + (8 - _source_tier(c)) * _SOURCE_TIER_WEIGHT

    def retrieve(self, query: str, k: int = 5, mode: str = "hybrid") -> list[dict]:
        # Wider candidate pool for ALL modes so a near-miss code chunk can be
        # re-ranked above generic docs by the symbol/source boost.
        k_cand = max(k * 8, 40)
        qtokens = set(_tok(query))

        if mode == "lexical_only":
            base = self._norm(self._lex_score(query, k_cand))
            lex_n, den_n = base, {}
        elif mode == "dense_only":
            base = self._norm(self._dense_score(query, k_cand))
            lex_n, den_n = {}, base
        else:  # hybrid
            lex_n = self._norm(self._lex_score(query, k_cand))
            den_n = self._norm(self._dense_score(query, k_cand))
            base = {i: self.lex_w * lex_n.get(i, 0.0) + self.dense_w * den_n.get(i, 0.0)
                    for i in (set(lex_n) | set(den_n))}

        final = {i: base[i] + self._rerank_bonus(qtokens, i) for i in base}
        top = sorted(final, key=lambda x: final[x], reverse=True)[:k]
        out = []
        for rank, i in enumerate(top):
            res = self._make_result(rank + 1, i, lex_n.get(i, 0.0), den_n.get(i, 0.0),
                                    final[i], mode if mode != "lexical_only" else "lexical_only")
            c = self.chunks[i]
            res["base_score"] = round(base[i], 4)
            res["symbol_boost"] = round(_symbol_boost(qtokens, c), 4)
            res["source_tier"] = _source_tier(c)
            res["chunk_type"] = "code" if c.get("source_type") == _CODE_SOURCE_TYPE else "doc"
            out.append(res)
        return out

    @property
    def dense_available(self) -> bool:
        return self.embeddings is not None and self._load_model()


# ── Factory ───────────────────────────────────────────────────────────────────

def load_retriever(
    lexical_weight: float = DEFAULT_LEX_W,
    dense_weight: float = DEFAULT_DENSE_W,
    prefer_canonical: bool = True,
) -> HybridRetriever:
    """Load the retriever. CONTROL-2C: prefers the canonical code-aware index
    when present; otherwise falls back to the doc-only index WITH a printed
    warning (no SILENT fallback) and a rebuild instruction.
    """
    use_canonical = prefer_canonical and CANONICAL_CHUNKS_PATH.exists()
    chunks_path = CANONICAL_CHUNKS_PATH if use_canonical else DOC_CHUNKS_PATH
    if not use_canonical:
        print(
            "[hybrid_retrieval] WARNING: canonical code-aware index not found at "
            f"{CANONICAL_CHUNKS_PATH.relative_to(ROOT)} — using DOC-ONLY index "
            "(no production code). Rebuild: python scripts/ai/build_canonical_brain_index.py",
            file=sys.stderr,
        )

    chunks: list[dict] = []
    with open(chunks_path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                chunks.append(json.loads(line))

    embeddings = None
    meta: list[dict] = []
    model_name = "all-MiniLM-L6-v2"

    # Dense embeddings must align with the chunk set. Canonical chunks use the
    # canonical dense dir; doc-only chunks use the committed doc dense dir.
    emb_path = (CANONICAL_DENSE_DIR / "chunk_embeddings.npy") if use_canonical else EMB_PATH
    meta_path = (CANONICAL_DENSE_DIR / "chunk_embedding_meta.json") if use_canonical else META_PATH
    if _HAS_NP and emb_path.exists() and meta_path.exists():
        embeddings = np.load(str(emb_path))  # type: ignore[union-attr]
        with open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)

    if CFG_PATH.exists():
        with open(CFG_PATH, encoding="utf-8") as f:
            cfg = json.load(f)
        model_name = cfg.get("model_name", model_name)

    return HybridRetriever(
        chunks=chunks,
        embeddings=embeddings,
        meta=meta,
        model_name=model_name,
        lexical_weight=lexical_weight,
        dense_weight=dense_weight,
    )


# ── CLI demo ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    query = " ".join(sys.argv[1:]) or "How does HSTS prevent downgrade attacks?"
    mode = "hybrid"
    print(f"Query: {query!r}  mode={mode}")
    r = load_retriever()
    results = r.retrieve(query, k=5, mode=mode)
    for res in results:
        print(f"  #{res['rank']} {res['score']:.4f} [{res['phase']}] "
              f"{res['title']} | lex={res['lexical_score']:.3f} den={res['dense_score']:.3f}")
        print(f"     {res['snippet'][:100]}")
